version: "3.9" # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_CLUSTER: ${DB_CLUSTER}
      G_CLIENT_ID: ${G_CLIENT_ID}
      G_CLIENT_SECRET: ${G_CLIENT_SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      SECRET: ${SECRET}
      NODE_ENV: ${NODE_ENV}
      G_GEOCODE_KEY: ${G_GEOCODE_KEY}
      S_SECRET_KEY: ${S_SECRET_KEY}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
